FROM syncthing/syncthing:latest
COPY client/config.xml /var/syncthing/config/config.xml
COPY client/cert.pem /var/syncthing/config/cert.pem
COPY client/key.pem /var/syncthing/config/key.pem
RUN chown -R 1000:1000 /var/syncthing/config && mkdir -p /var/syncthing/testuser && chown 1000:1000 /var/syncthing/testuser
ENV STNOUPGRADE=1 STNODEFAULTFOLDER=1
